### ISSUE TITLE
Downloading from the Cloud hangs Armorpaint - Linux

### ISSUE THREAD

**Issue by YAFU** [armory3d/armortools#1039]
**ArmorPaint version:**
Built from master on June 30 
ArmorPaint.org - v0.8 (2021-06-30) - aeb9080

**OS/device including version:**
Kubuntu 20.04 (Linux) - GTX 960 - 460.84 driver

**Issue description:**
Hello.
When I open the Browser, Cloud and some folder it starts to download correctly until it returns a long list of errors of the type: 
```
Trace: TypeError: Cannot read property 'width' of undefined
    at kha_Image.get_width (<anonymous>:3674:30)
    at <anonymous>:11383:53
    at Array.render (<anonymous>:4428:6)
    at Function.render (<anonymous>:44206:35)
    at renderCallback (<anonymous>:44262:14)
X connection to :0 broken (explicit kill or server shutdown).
```
At this point Armorpaint hangs and I must kill the application.
I have found old similar reports closed as solved. I have wget installed and Armorpaint has permission to write to disk.

**Comment by BrainBlasted** [comment]
Also getting this.

**ArmorPaint version:**
Built from master on July 3
ArmorPaint.org - v0.8 - 48b64d157775ed59e7d42714d629fbb744864e5e

**OS/device including version:**
Fedora 34 - RX 5700 XT

**Comment by The-EDev** [comment]
+1

**ArmorPaint version:**
Installed armorpaint-git from AUR
ArmorPaint.org - v0.8 (2021-06-16) - e72478b

**OS/device including version:**
5.10.42-1-MANJARO (X11) - GTX 980Ti - 465.31 driver

**Comment by StrandedAlien** [comment]
Does not hang anymore, at least on Manjaro Linux. However, still does not work and i can´t see any icons.

**Comment by YAFU** [comment]
> Does not hang anymore, at least on Manjaro Linux. However, still does not work and i can´t see any icons.

Hi.
See here:
https://github.com/armory3d/armorpaint/issues/1231#issuecomment-1105675465

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armortools/issues/1231.
