### ISSUE TITLE
ArmorPaint hung After Import from blender when try to access Cloud material 

### ISSUE THREAD

**Issue by lnasto** [armory3d/armortools#1090]
*ArmorPaint 0.8-9e8e31f, Windows*

**Issue description: After i successfully import an object and go to browser > Cloud > materials\cc0 application hung Also material sample images is missing and if i maximize or minimize screen get black**

**Steps to reproduce: Open Blender select default cube and use ArmorPaint plugin (v= 1.1.0) to open it then in ArmorPaint go to browser selecting Cloud it freeze . If i go in (local) Disk i can open downloaded material (Also material sample images is missing but it work)**

**Comment by luboslenco** [comment]
Hello, thanks for report. Which Windows version?

**Comment by luboslenco** [comment]
Is the Blender step important? Is cloud working ok otherwise?

**Comment by lnasto** [comment]
Yes, I think it is very important for speed up work.
 it is super fast with one button send - load object in ArmorPaint and
after finish paint it loads textures easy to blender again.
Loading textures to blender from plug in need a small correction i think
except dase color all other Color Space need to set Non-color.

If I import mesh .blender Cloud it look's to working normally.
but it is super easy and fast to work with plugin.

Thank you.



Στις Σάβ, 14 Αυγ 2021 στις 12:21 μ.μ., ο/η Lubos Lenco <
***@***.***> έγραψε:

**Comment by lnasto** [comment]
I manage to correct the small problem with Color Space. I set all others
in Non-Color
may i upload the code?

Στις Τετ, 18 Αυγ 2021 στις 9:48 μ.μ., ο/η Labros Nastos <
***@***.***> έγραψε:

**Comment by SlincHD** [comment]
the freezing is also acuring when i open a saved armorpaint file

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armortools/issues/1618.
