### ISSUE TITLE
Browser, Can't see my brushes before I use them

### ISSUE THREAD

**Issue by NLEGITN** [armory3d/armortools#1147]
*ArmorPaint 0.8-e11cf49, Windows*

**Feature description:**

Any scene you might be working on you have the Browser at the bottom.  You can find your files just file but they just look like files.  You can't see a preview of what they would look like.  This would be awesome...

**Comment by MathemanFlo** [comment]
This is a good extension of #814 especially of https://github.com/armory3d/armorpaint/issues/814#issuecomment-845786240 where the same is proposed for materials.
