### ISSUE TITLE
Error: Check internet connection to access the cloud?

### ISSUE THREAD

**Issue by Lux-D-Aeterna** [armory3d/armortools#1240]
Version 08 non-dev

Windows 10 Pro
BaseBoard Product	TUF GAMING X570-PLUS (WI-FI)
AMD Ryzen 9 3950X 16-Core Processor, 3700 Mhz, 16 Core(s), 32 Logical Processor(s)
128GB DDR4 3600MHz Ram
Nvida GeForce RTX 3080 Driver 497.29

Recently purchased Armour Paint on Gumroad and downloaded Version 08 non-dev for windows; Opened it up everything else seems to work fine, but when going to the cloud to see anything inside I get an Error: Check internet connection to access the cloud. I don't know where to start to look. I ran it as admin and it still gives the same issue.

![ArmorPaint_JaHQwQbgty](https://user-images.githubusercontent.com/98114219/150389174-2118d181-b69a-402b-864b-b5c2983aa3e1.png)

**Comment by lionkor** [comment]
Same issue here, on Linux

**Comment by aurkaxi** [comment]
Same on linux

**Comment by luboslenco** [comment]
Windows builds should be resolved, thanks for report. For Linux investigating at https://github.com/armory3d/armortools/issues/1231.
