### ISSUE TITLE
Black screen on importing .fbx (iPad)

### ISSUE THREAD

**Issue by sharpaccent** [armory3d/armortools#1360]
Basically what the title says, I just bought the app and when tried to import an .fbx the viewport goes all black.
Also the report bug button under info doesnt work 

Do let me know if you aware of this or if i just burned 16 euros

**Comment by zack7234** [comment]
I'm having the same issue

**Comment by luboslenco** [comment]
Is the issue still present in the latest iPad version? If so, can you please attach a zipped .fbx file here? Will investigate and fix.

**Comment by luboslenco** [comment]
If the issue persists please let me know.
