### ISSUE TITLE
Perlin Noise is Blocky on AMD GPU

### ISSUE THREAD

**Issue by Teetle-Beetle** [armory3d/armortools#1374]
**ArmorPaint version:**
ArmorPaint 0.8 win64

**Issue description:**
Perlin Noise texture is blocky on AMD Radeon RX 5700 GPU and AMD Ryzen 7 1700X:
![paubt](https://user-images.githubusercontent.com/72716561/163640115-a25ad498-8743-4003-a527-74acaf67ea51.png)

Nvidia GeForce RTX 2070 and AMD Ryzen 9 5950X:
![image](https://user-images.githubusercontent.com/72716561/163641204-a1d8c25d-e7f4-4994-b1b4-6c4c8edcbba6.png)

**Comment by luboslenco** [comment]
Hopefully fixed now when using the latest drivers + latest 0.9dev builds, unable to test myself as of now, sorry.
