### ISSUE TITLE
Upper Polygon Limit.

### ISSUE THREAD

**Issue by modtim** [armory3d/armortools#1446]
Hi all!

Thanks for the amazing app. 

I've been having issues loading large assets (~30m as both obj and fbx). I've tried this on a number of different systems and build versions. The ones I've tested importing the asset on is.

Linux - vulkan
Linux - regular
Windows - DX
Windows - regular

It almost immediately crashes on import. The dump is pretty light and has just a "The thread tried to read from or write to a virtual address for which it does not have the appropriate access." with an exception code of 0xC0000005. No heap info. 

I've thrown a ton of different hardware configurations at it as well with the upward being 128gb of ram and a 3080 ti. 

I was more than happy to purchase a license for this application as it appears to be a wonderful idea but I'm feeling a little lost on how to get it to perform.

**Comment by modtim** [comment]
Got an interesting trace on Linux. JS memory pressure issue. "External Memory Pressure GC in old space requested"

**Comment by modtim** [comment]
bump

**Comment by luboslenco** [comment]
Sorry it took so long. Pushed some improvements in the latest 0.9dev builds, more in the works:
- 1.3GB .obj now loads
- 4.3GB .obj still fails - will fix

**Comment by luboslenco** [comment]
Pushed more improvements - tested on 3.7GB .obj which now loads fine, ~45M tris. Hopefully it now handles your original assets. Will go above 4.3GB for v1.0.
