### ISSUE TITLE
VKRT | git apply - patch does not apply

### ISSUE THREAD

**Issue by A31Nesta** [armory3d/armortools#1449]
**OS/device including version:** Arch Linux | Linux 5.15.67-1-lts (64 bits)

**Issue description:**
Can't apply patch trying to build with Vulkan Path Tracing.
It says patch does not apply. I also tried using `--3way`. With that I managed to get the patch to apply except for the Vulkan.c.h file.
The output is:

> error: patch failed: Backends/Graphics5/Vulkan/Sources/kinc/backend/graphics5/Vulkan.c.h:53
error: Backends/Graphics5/Vulkan/Sources/kinc/backend/graphics5/Vulkan.c.h: patch does not apply

From reading that I got that there was an issue in line 53 so I checked it and I saw that it's an empty line between two lines that appear to be perfectly fine:
`52 | kinc_g5_render_target_t *vulkanRenderTargets[16] = {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL};`
`53 |`
`54 | static bool began = false;`

**Steps to reproduce:**
- Follow the instructions:
  - `git clone --recursive https://github.com/armory3d/armorpaint`
  - `cd armorpaint`
 - Follow the instructions for VKRT:
   - `git clone --recursive https://github.com/armory3d/glsl_to_spirv armorcore/Libraries/glsl_to_spirv`
   - `git apply armorcore/patch/vulkan_raytrace.diff --directory=armorcore/Kinc`

The error happens after executing the git apply command.

**Comment by NicTanghe** [comment]
Could this be the same issue I`m ruinning into with this ?

```
git clone --recursive https://github.com/armory3d/glsl_to_spirv armorcore/Libraries/glsl_to_spirv
git apply armorcore/patch/vulkan_raytrace.diff --directory=armorcore/Kinc
armorcore/Kinc/make --from armorcore -g vulkan --compiler clang --compile
cd armorcore/Deployment
strip ArmorPaint
./ArmorPaint ../../build/krom
Cloning into 'armorcore/Libraries/glsl_to_spirv'...
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 31 (delta 12), reused 25 (delta 9), pack-reused 0
Receiving objects: 100% (31/31), 25.19 KiB | 45.00 KiB/s, done.
Resolving deltas: 100% (12/12), done.
Submodule 'glslang' (https://github.com/Kode/glslang) registered for path 'glslang'
Cloning into '/home/ntanghe/git/armorcore/Libraries/glsl_to_spirv/glslang'...
remote: Enumerating objects: 42388, done.
remote: Total 42388 (delta 0), reused 0 (delta 0), pack-reused 42388
Receiving objects: 100% (42388/42388), 56.21 MiB | 363.00 KiB/s, done.
Resolving deltas: 100% (35610/35610), done.
Submodule path 'glslang': checked out 'af0ceb28ebd1d2a63a64a5c1b1a8ec55b608dbdb'
error: can't open patch 'armorcore/patch/vulkan_raytrace.diff': No such file or directory
zsh: no such file or directory: armorcore/Kinc/make
cd: no such file or directory: armorcore/Deployment
strip: 'ArmorPaint': No such file
zsh: no such file or directory: ./ArmorPaint
```

**Comment by A31Nesta** [comment]
Yes, it's the same error. Everything was cloned as it should but the patch doesn't apply.

**Comment by NicTanghe** [comment]
Im here to ask plz open ticket  [#1458](https://github.com/armory3d/armorpaint/issues/1459)

**Comment by rpaladin** [comment]
@NicTanghe since you self-closed your own issue, Github still allows you to reopen it yourself. 🙂

**Comment by lylythechosenone** [comment]
What's the status on this? It's been over 6 months now since the last comment.

**Comment by Razzaline** [comment]
[vulkan_raytrace.txt](https://github.com/armory3d/armortools/files/11909693/vulkan_raytrace.txt)
I made an attempt to update it with my limited knowledge, but I'm sure there are plenty of problems.

I get these errors when trying to compile with the new patch:

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at node:kmake/Project:106:45
    at new Promise (<anonymous>)
    at loadProject (node:kmake/Project:73:12)
    at Project.addProject (node:kmake/Project:635:31)
    at Object.flags.on_project_created (eval at <anonymous> (eval at <anonymous> (node:kmake/Project:109:27)), <anonymous>:18:17)
    at eval (eval at <anonymous> (node:kmake/Project:109:27), <anonymous>:238:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Error: kfile did not call resolve, no project created.
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:119:11)
    at Object.resolve (node:path:1098:7)
    at node:kmake/Project:106:45
    at new Promise (<anonymous>)
    at loadProject (node:kmake/Project:73:12)
    at Project.addProject (node:kmake/Project:635:31)
    at Object.flags.on_project_created (eval at <anonymous> (eval at <anonymous> (node:kmake/Project:109:27)), <anonymous>:18:17)
    at eval (eval at <anonymous> (node:kmake/Project:109:27), <anonymous>:238:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'

**Comment by lylythechosenone** [comment]
I get the same error even without the patch. See #1585.

**Comment by Razzaline** [comment]
Huh, okay... so maybe it's not my patch then? Sadly the errors aren't very helpful, and I don't know how to troubleshoot from here.

I only get those errors you have with the OpenGL build when trying to build the Vulkan version unpatched, though (but not with the OpenGL one; it compiles and runs just fine).

**Comment by NicTanghe** [comment]
Can someone test to c if Razzline`s patch works with  clang 14 ?

**Comment by luboslenco** [comment]
Fixed now! Thanks for reports.
