### ISSUE TITLE
Build fails - "Windows VR wip" version

### ISSUE THREAD

**Issue by ikonnow** [armory3d/armortools#1457]
**Issue description:**
Seams like the "Direct3D11.h" file, requested by the script VrInterface_Oculus.cpp doesn't exist. - This results in a build error 
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'Direct3D11.h': No such file or directory	ArmorPaint	"armorpaint\armorcore\Kinc\Backends\Graphics4\Direct3D11\Sources\kinc\backend\VrInterface_Oculus.cpp	5"	

**Steps to reproduce:**
Build solution in VS - after building with the command
armorcore\Kinc\make --from armorcore -g direct3d11 --vr oculus
<img width="445" alt="image" src="https://user-images.githubusercontent.com/25803775/195295755-68fc0d91-30a6-4cf4-a87d-78a2dbc4d2ad.png">

**Comment by ikonnow** [comment]
Is there any way to get around it? Would love to try the VR Version

**Comment by luboslenco** [comment]
Sorry, will try to get to it eventually but as of now VR version still not ready.
