### ISSUE TITLE
Side menu on the Ipad collapses

### ISSUE THREAD

**Issue by lublak** [armory3d/armortools#1489]
**ArmorPaint version:**
0.9.22.12

**OS/device including version:**
iPad 16.2 IPad Pro 2022

**Issue description:**

The side menu collapses uncontrollably. Whenever I interact with the side menu (mostly the tabs) it can happen randomly. Problem here is also that the reopening can lead to it collapsing again. It can sometimes take several tries to switch between layers and plugins as an example.
I switch to plugins: menu is automatically collapsed.
Then I have to try several times to get it apart again.
And when switching back the same.

**Steps to reproduce:**

The "<<":

<img width="633" alt="Bildschirmfoto 2023-01-03 um 10 50 53 png" src="https://user-images.githubusercontent.com/44057030/210334718-08f5c5de-9280-4b16-a696-54cae0d6a159.png">

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armortools/commit/8c9ba711e343d71eac1fabe599290c13091f1ffe, appstore update coming soon. Thanks for report.

**Comment by lublak** [comment]
> Pushed a fix at https://github.com/armory3d/armortools/commit/8c9ba711e343d71eac1fabe599290c13091f1ffe, appstore update coming soon. Thanks for report.

Thanks for the fix 😄
