### ISSUE TITLE
No smooth zoom

### ISSUE THREAD

**Issue by lublak** [armory3d/armortools#1490]
**ArmorPaint version:**
0.9.22.12

**OS/device including version:**
iPad 16.2 IPad Pro 2022

**Issue description:**

Currently if you zoom with gesture its not smooth. Its step based like on a scroll wheel.

**Comment by luboslenco** [comment]
Still needs more tweaks but it should no longer work like a scroll wheel.

**Comment by lublak** [comment]
@luboslenco yes. It's smooth now :)
