### ISSUE TITLE
Finger navigation move-rotate-zoom

### ISSUE THREAD

**Issue by Masterkopet** [armory3d/armortools#1495]
*ArmorPaint 0.9-8bd04fa, iPad-BFEE9CF4-3C3A-4DA7-ADED-3A3B668DC8E1
My device iPad Pro M1

I use AP with apple pencil and not using keyboard.
I feel abit difficult to navigate with finger (zoom : pinch 2 finger, rotate : 3 finger)
I hope finger navigate will be change to standard like other App (example : nomadsculp)
Rotate object : swipe 1 finger
Zoom object : piinch 2 finger
Move object : swipe 2 finger
Undo : tab 2 finger
Redo : tab 3 finger
Etc

Thank you.

**Comment by lublak** [comment]
Duplicated #1484

**Comment by luboslenco** [comment]
Will implement at https://github.com/armory3d/armortools/issues/1484, thanks for the suggestion.
