### ISSUE TITLE
Materials not importing

### ISSUE THREAD

**Issue by Leonidas300** [armory3d/armortools#1496]
**ArmorPaint version:**

![Screenshot_20230110_194448](https://user-images.githubusercontent.com/187730/211634328-fbd8b7e4-fbe5-428d-a096-c7cdb610968c.png)

**OS/device including version:**
Nvidia Geforce GTX 960 4GB
Linux - Manjaro 5.15

**Issue description:**
After Upgraded to this version when I import I get black character, materials not loaded and this in console:
![Screenshot_20230110_194336](https://user-images.githubusercontent.com/187730/211634604-d0776317-d7a3-4cab-ba65-a0497b62c64f.png)

When I press Import without mesh just materials from materials window materials are normally shown. When I press import in materials after import scene, I get this in console:

![Screenshot_20230110_194427](https://user-images.githubusercontent.com/187730/211634888-54946252-aeae-4e08-a91f-a0cb7b457c0f.png)

**Steps to reproduce:**
Just import scene.

**Comment by luboslenco** [comment]
> getAtlasObjects

Looks like it's related to the atlas functionality but I do not know how to reproduce it. If you still get this issue in the latest version then attaching a zipped .arm file for testing is welcome.
