### ISSUE TITLE
ArmorLab stops responding after double-clicking .txt in content browser

### ISSUE THREAD

**Issue by GuiltyPixel** [armory3d/armortools#1508]
*ArmorLab 0.1-66e12fa, Windows*

**Issue description:**
ArmorLab becomes unresponsive when attempting to open a .txt file. Expected to launch system specified editor or preview contents in ArmorLab.

**Steps to reproduce:**
Navigate "cloud" documents in the browser panel on the bottom of the main UI. Step into decals, double click the readme.txt

**Comment by luboslenco** [comment]
Appears to be resolved now, thanks for report!
