### ISSUE TITLE
Why Armortools now?

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armortools#1514]
Why was Armorlab moved to this reposet and why was Armorpaint renamed to "armortools"?

**Comment by luboslenco** [comment]
Mainly a folder restructuring, so it's easier for me to keep paint and lab in sync and share more code. You can still find paint sources at https://github.com/armory3d/armortools/tree/main/armorpaint.

**Comment by rpaladin** [comment]
I'm curious, are the original ArmorPaint / ArmorLab repositories going to be archived, or are you perhaps planning to use them as submodules repositories?
