### ISSUE TITLE
Unable to maximize window

### ISSUE THREAD

**Issue by icyboxs** [armory3d/armortools#1517]
When I maximize the window ArmorPaintDXR doesn't respond and then disappears.
I don't seem to find any log files and I'm not familiar with the software directory structure if need log files, please tell me where

**Comment by icyboxs** [comment]
> 
I downloaded it from the official website and it seems that I downloaded the wrong version
Correct ArmorPaintDXR not ArmorPaint....


I use Windows 10 22H2

ArmorPaint.org - v0.9 (2023-02-04) - 4ec16d3
Windows - Direct3D12
NVIDIA GeForce RTX 3070 Ti

**Comment by luboslenco** [comment]
Hopefully all is good now -  both versions should maximize properly.
