### ISSUE TITLE
Swatch Drag and drop broken in ArmorLab

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armortools#1518]
**ArmorPaint version:**
ArmorLab.org - v0.1 (2023-02-14) - cf5e720
Windows - Direct3D11

**OS/device including version:**
Windows 11

**Issue description:**
Swatches allow for reordering via drag and drop. In ArmorLab this feature does not work (in contrast to ArmorPaint)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armortools/commit/9471eeca54d7a19d6449575c3955c4533ba1aedb, thanks for report.
