### ISSUE TITLE
Viewport scale changed and not resetting. Can`t use the ArmorPaint anymore

### ISSUE THREAD

**Issue by lucrybpin** [armory3d/armortools#1526]
*ArmorPaint 0.9-4ec16d3, Windows*

**Issue description:**

**Steps to reproduce:**
CTRL+K -> Viewport -> (some scale viewport setting)

**Comment by luboslenco** [comment]
Can you provide more detail? What is a scale viewport setting? Do you mean resizing the window?

**Comment by lucrybpin** [comment]
Hi!

I am sorry for such a poor description

To reproduce you need a monitor under 32"

Steps:
Open ArmorPaint -> [Menu] Edit -> Preferences... -> [Tab] Interface -> Drag UI Scale to a very high value

Possible Solutions:
• The "Reset Layout" could be accessible from the top menu. In my computer the top menu was still usable for the first buttons (File, Edit, Viewport)
• Save the UI Scale value and Interface configs in a (json?) file that can be edited in the ArmorPaint folder, just like you did in keymap_presets.


I've noticed that even if you delete and install again the ArmoPaint, the problem persists.
Yesterday a figured out a workaround that was changing my monitor orientation so I could open ArmorPaint and change it back.

Thank you for the attention and great work.

________________________________
De: Lubos Lenco ***@***.***>
Enviado: quarta-feira, 1 de março de 2023 06:51
Para: armory3d/armortools ***@***.***>
Cc: Lucas Rybzinski ***@***.***>; Author ***@***.***>
Assunto: Re: [armory3d/armortools] Viewport scale changed and not resetting. Can`t use the ArmorPaint anymore (Issue #1526)


Can you provide more detail? What is a scale viewport setting? Do you mean resizing the window?

**Comment by MathemanFlo** [comment]
I think the problem is the follwing:
![grafik](https://user-images.githubusercontent.com/28649121/222691232-ef34219c-c2a7-4e08-8ae1-cd0c3c8760c4.png)
Now there is no way to reset the ui scale nor to restore the default settings.
