### ISSUE TITLE
Issues with loading cloud materials

### ISSUE THREAD

**Issue by BB26CG** [armory3d/armortools#1529]
(WIN11, Issue occurs on 0.9dev build)
When attempting to load any ambientCG materials from cloud, the program will hang and have to be force-quit every time, occurs every time. When attempting to load procedural  / scanned materials from cloud, the application will either remain 'responding' but not respond to user inputs, other times it will stop responding to inputs for only a few seconds, then inputs will work, the texture will not load however. Additionally, thumbnails for the materials do not load correctly in-editor either.

**Comment by BB26CG** [comment]
Issue no longer present in new build, thumbnails load correctly and program eventually stops hanging after loading thumbnails for materials. Ignore this report, sorry.

**Comment by luboslenco** [comment]
Glad to hear it is working now, thanks for report.
