### ISSUE TITLE
Adding «.hdr» files in the viewport crush Armorpaint

### ISSUE THREAD

**Issue by infinder** [armory3d/armortools#1530]
ArmorPaint.org - v0.9 (2023-03-08) - c0f1b19
Windows 11 - Direct3D11
Intel(R) HD Graphics 620

Drag & drop .hdr files in the viewport crushes Armorpaint.

**Comment by MathemanFlo** [comment]
I believe I know this issue and I'm sure it is very similar to #628. I'm still facing this problem. Sometimes ArmorPaint crashes while setting bigger hdr images as env map. Loading them as texture typically works fine, setting them as env map crashes ArmorPaint. Only a `kinc.dmp` is created, no Haxe/JavaScript error.

**Comment by infinder** [comment]
well, it used to work well that way though..

**Comment by MathemanFlo** [comment]
I see. I'm sorry.
I can not test it on the same system but a similar one:
ArmorPaint.org - v0.9 (2023-03-08) - c0f1b19
Windows - Direct3D11
Intel(R) UHD Graphics 630

Here it works for smaller hdr files ( ~500kb, 360x180 pixel)
![grafik](https://user-images.githubusercontent.com/28649121/223689339-4a0e54a9-8eb7-4f73-bed4-ae90f8f679ca.png)

But I get crashes for bigger one (4k hdr) as you describe in most cases (say 19 out of 20 cases), but sometimes it works
![grafik](https://user-images.githubusercontent.com/28649121/223691154-5931c601-d15b-4066-bee0-65bff140b0bc.png)

**Comment by luboslenco** [comment]
Do you get the crash with every .hdr file you try? Or do some .hdrs work and some do not?

**Comment by rpaladin** [comment]
Perhaps the crash is related to https://github.com/armory3d/armory/issues/2746?

**Comment by infinder** [comment]
ArmorPaint.org - v0.9 (2023-05-15) - 62d44ba
Windows - Direct3D11
Intel(R) HD Graphics 620

It keeps crashing with all hdrs files. Files from cloud/hdrheaven apeear with thumbnails but from ambientcg they don't..

**Comment by infinder** [comment]
In my second laptop with nvidia 3060 graphics card and 16gb ram, 4k hdr files are loaded fine but after draging 3-4 files in a row in the viewport  there is a lag and the last one appears after a while. It's  like the previously loaded hdr files occupied the system memory and they don't released it right away.  Regarding to thumbnails the situation remains the same.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armortools/issues/1627.
