### ISSUE TITLE
Support for multibyte utf8 glyphs is broken

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armortools#1531]
**ArmorPaint version:**
ArmorPaint.org - v0.9 (2023-03-08) - c0f1b19

**OS/device including version:**
Windows - Direct3D11

**Issue description:**
ArmorPaint does not treat 'äöü€' and similar multibyte glyphs correctly anymore.

**Steps to reproduce:**

1. Switch to the German (DE) locale or any other locale that uses non ascii (i.e. non 1 byte characters) like the greek locale where ArmorPaint is completely unusable at the moment
2. Close ArmorPaint
3. Open the "Camera" menu

The first entry should be "Zurücksetzen" (reset), but the 'ü' is missing now.
![grafik](https://user-images.githubusercontent.com/28649121/223669690-eec2d3eb-448f-4a19-bd33-1893d77200be.png)
I believe the glyphs are not loaded correctly. 
Because if the user goes to the Script tab and types these glyphs, then the behavior changes:
![grafik](https://user-images.githubusercontent.com/28649121/223670712-6f5eb2dd-9f3f-491a-a070-0ccaaf78a8e3.png)

Second observation:
Switching to EN and back to DE (after step 3) fixes the rendering problem.
![grafik](https://user-images.githubusercontent.com/28649121/223671138-d4c8dc8b-983d-44e7-833d-b3304758ccd8.png)
But the carret in the script tab is still at the "number of bytes" position and not the "number of glyphs"/"text font width" position 
![grafik](https://user-images.githubusercontent.com/28649121/223671509-73284ad0-556a-4e7b-b20c-a2a45c5a9967.png)

Example with greek loale
![grafik](https://user-images.githubusercontent.com/28649121/223672093-66799e81-29ea-43da-a263-b739c13a2048.png)

**Comment by luboslenco** [comment]
Hopefully all good now.

**Comment by MathemanFlo** [comment]
Yes. The issue is definitely fixed. Thank's a lot.
