### ISSUE TITLE
Crashing when creating inpaint node.

### ISSUE THREAD

**Issue by squeige** [armory3d/armortools#1536]
*ArmorLab 0.1-f11b359, Windows*

Whenever I create an inpaint node application immediately exits.

Fresh new scene, add inpaint 
![Screenshot 2023-03-10 222034](https://user-images.githubusercontent.com/50630172/224464556-4e0fe0b4-f90c-4112-aa7c-68af7aa42f3a.png)

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armortools/commit/539fd2b8cb1aa894e121ef90d797c2f6f8c54bb8 in newly updated builds. Thanks for report!

**Comment by squeige** [comment]
Fixed thanks.
