### ISSUE TITLE
Giving layers specific Color IDs

### ISSUE THREAD

**Issue by corviraptor** [armory3d/armortools#1538]
*ArmorPaint 0.9-b8a5656, Windows*

**Feature description:**
I have very limited experience with texture software, but from my short time with Mixer I found that assigning layers specific color IDs felt really intuitive. As a new user, I am currently struggling to work with ArmorPaint's color ID system. I find myself having to return to the color ID tool over and over again and accidentally assigning materials I didn't want, and I can't really figure out how the tool actually works.

It would be much easier for me if there were the capability to assign a material layer color IDs and avoid touching the color ID tool when working with materials- I don't want to keep fiddling with it. If this feature does actually exist, and I just missed it, it's difficult to find.

**Comment by MathemanFlo** [comment]
I think your use case is already supported
1. Load your color map
2. Select it
3. Now create all channels you would like to assign ids to
4. Select the first layer you want to assign an id to
5. Now pick colors in the color ID tool
6. Click on to mask
7. Repeat this procedure until you have assigned all ids to layers.
8. **Clear the picked color**
9. Now you never have to return to the picker tool again and can paint the layers you want to paint.

You can even assign multiple ids to one layer or one id to multiple layers. Everything is possible.

![grafik](https://user-images.githubusercontent.com/28649121/224656040-f658f400-632d-4748-9423-b870847fedc1.png)

The end result looks as follows:
![grafik](https://user-images.githubusercontent.com/28649121/224656206-dddef06b-c1a9-4898-bb43-289eccc7f09e.png)

You probably used the other workflow where the user picks an id, paints, picks another id, paints, ...

**Comment by corviraptor** [comment]
This appears to work, thank you very much!

**Comment by MathemanFlo** [comment]
@luboslenco made a great tutorial video to demonstrate the workflow: [YouTube - Color ID Masks](https://m.youtube.com/watch?v=wHjLNLrAmZo)

**Comment by luboslenco** [comment]
Got inspired here, thanks for posting this. :) Can still try to improve the workflow - feel welcome to open more issues.
