### ISSUE TITLE
AmorPaint segfaults when importing OBJ files from Wings3D

### ISSUE THREAD

**Issue by virtualritz** [armory3d/armortools#1539]
**ArmorPaint version:**
34c316b8f8cd34a0ab1eb9646e11e313028d13df

**OS/device including version:**
Linux (Ubuntu 22.04).

**Issue description:**
Trying to import any OBJ file generated from Wings3D makes `AmorPaint` segfault.

**Steps to reproduce:**
Try the attached sample file ([cube.zip](https://github.com/armory3d/armortools/files/10970630/cube.zip)).

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorcore/commit/c5f14d72e9d952341b89515326dd632b788beba4, thanks for report!
