### ISSUE TITLE
Reading non UTF-8 files brings in an invalid state

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armortools#1542]
If the user tries to import this (ANSI encoded) file: [error_example.txt](https://github.com/luboslenco/armorpad/files/10733099/error_example.txt) ArmorLab (as well as ArmorPaint,...) switches to a invalid state and a stderror is produced due to a invalid code point.
[stderr.txt](https://github.com/luboslenco/armorpad/files/10733096/stderr.txt)

**Comment by luboslenco** [comment]
Will no longer crash but only displays an error for now. Thanks for report. https://github.com/armory3d/armortools/commit/5759780e09060624d92389e3a8edca6b9eeabad0
