### ISSUE TITLE
Error compiler armorlab

### ISSUE THREAD

**Issue by angelbpineda** [armory3d/armortools#1544]
PS E:\Apps\Armortools\armorlab> ..\armorcore\Kinc\make --from ..\armorcore -g direct3d11
Using Kinc (cc564857) from E:\Apps\Armortools\armorcore\Kinc
kfile found.
Creating Windows project files.
Using Kha from E:\Apps\Armortools\armorcore
Creating Kha project.
Exporting asset 1 of 5 (default_brush.arm).
Exporting asset 2 of 5 (icons.png).
Exporting asset 3 of 5 (icons2x.png).
Exporting asset 4 of 5 (placeholder.png).
Exporting asset 5 of 5 (Scene.arm).
..
...
Compiling shader 35 of 38 (supersample_resolve.frag.glsl).
Compiling shader 36 of 38 (taa_pass.frag.glsl).
Compiling shader 37 of 38 (world_pass.frag.glsl).
Compiling shader 38 of 38 (world_pass.vert.glsl).
Compiling shader 1 of 3 (voxel_pos.frag.glsl).
Compiling shader 2 of 3 (voxel_pos.geom.glsl).
Compiling shader 3 of 3 (voxel_pos.vert.glsl).
E:\Apps\Armortools\base\Sources/arm/render/RenderPathBase.hx:133: characters 129-139 : Identifier 'ToolSmudge' is not part of arm.WorkspaceTool
E:\Apps\Armortools\armorlab\Sources/arm/ui/UIHeader.hx:132: characters 18-33 : arm.TContext has no field blurDirectional

Haxe compiler error.
Error: kfile did not call resolve, no project created.
PS E:\Apps\Armortools\armorlab>

**Comment by luboslenco** [comment]
I think this one is fixed as of now, thanks for letting me know. Still planning to do further cleanup so some more errors may pop up in the near future.
