### ISSUE TITLE
Crash on saving any data

### ISSUE THREAD

**Issue by GRIMMoonwall** [armory3d/armortools#1547]
I have a few issues that is really preventing me from having any workflow. ill list them in bullets to make it easier to read. 
I am using armorpaint 09dev, 

- crashing on saving brushes
- crash on saving projects
- crash on saving materials 
- material icons disappear after using the program for a while
- sometimes the light engine dies and metallic no longer displays? not sure if explanation is correct
- most tutorials are outdated and very limited. 
- please add beval node for materials 
- why do brushes and materials not save?
- there needs to be a random direction node for brushes  so the angle is random. 
- sometimes the only way to fix certain issues is to delete the program and re unpack it from zip.

**Comment by luboslenco** [comment]
Which OS and GPU are you on? Sounds like armorpaint is unable to write anything to disk. Any anti-virus software which might be blocking it?

**Comment by GRIMMoonwall** [comment]
windows 10. nividia geforce gtx 1650. I don't have any antivirus besides the build in windows defender. IT does say it is a untrusted program when first opening but i usually skip that bit.

**Comment by GRIMMoonwall** [comment]
I seem to have somewhat fixed the issue by placing the armorpaint files into the same folder all my textures are located in being my documents folder.

**Comment by luboslenco** [comment]
Hm that's weird. Happy there was at least a workaround, I will try to keep an eye on that.
