### ISSUE TITLE
UV Unwrap crashes entire program

### ISSUE THREAD

**Issue by aalberti333** [armory3d/armortools#1550]
**ArmorPaint version:**
ArmorPaint_09dev_win64.zip

**OS/device including version:**
Windows 10 Home

**Issue description:**
After importing an obj from blender, I'm able to import the mesh, but as soon as the "unwrap uv" option comes up and I click unwrap (using either plugin) the entire program crashes.

**Steps to reproduce:**
File in question: https://1drv.ms/u/s!AoMB6bNB4EIzgtV6-1KH71Sv1RlgFw?e=TY2QYf

Import the mesh, and try unwrapping the UVs.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armortools/commit/2a27e9b0f2963c19f207ddb2291241afbe85bd4a, thanks for report!
