### ISSUE TITLE
Importing .obj meshes and splitting them by material causes ArmorPaint to crash

### ISSUE THREAD

**Issue by Valkinsenn** [armory3d/armortools#1551]
**ArmorPaint version:**
2bae92e63adf2499a9195cedef20f0993fd3c4dc

**OS/device including version:**
Windows 10 (22H2)

**Issue description:**
Attempting to open a .obj mesh file in ArmorPaint and split by materials causes a hard crash without warning, even on models that were successfully split by material before, like the Hydrant model from the official tutorial on YouTube.

**Steps to reproduce:**
Try to import any .obj files and split them by materials.

**Comment by luboslenco** [comment]
Should be resolved via https://github.com/armory3d/armorcore/commit/c22ad3fa5996146229402090c1288902cd4caf81, thanks for report!
