### ISSUE TITLE
Armor paint don't work again pt.2

### ISSUE THREAD

**Issue by Pro-pra** [armory3d/armortools#1555]
also see https://github.com/armory3d/armortools/issues/85

```
cd armorpaint
../armorcore/Kinc/make --from ../armorcore -g opengl --compiler clang --compile
...
Compiling shader 2 of 3 (voxel_pos.geom.glsl).
Compiling shader 3 of 3 (voxel_pos.vert.glsl).
/tmp/armortools-0.9/armorcore/Tools/haxe/std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
/tmp/armortools-0.9/base/Sources/arm/sys/BuildMacros.hx:19: characters 27-49 : Called from here
/tmp/armortools-0.9/base/Sources/MainBase.hx:20: characters 26-43 : Called from here

Haxe compiler error.
Error: kfile did not call resolve, no project created.
error: Bad exit status from /tmp/.private/lav/rpm-tmp.91485 (%build)
```

**Comment by Pro-pra** [comment]
Also i have this error on clang 16.0.0
In file included from ../../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/posixunit.c:4:
../../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/thread.c.h:67:2: error: call to undeclared function 'pthread_setname_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        pthread_setname_np(pthread_self(), name);
        ^
1 error generated.


I think need -Wno-error=implicit-function-declaration

**Comment by luboslenco** [comment]
I do not know why it's not working on your setup, sorry. :( Usually this error is resolved once git command is available in terminal.

If you inspect the line causing error:
https://github.com/armory3d/armortools/blob/main/base/Sources/arm/sys/BuildMacros.hx#L18

You can notice it is calling a git command - but fails for some reason. If you are not able to get past it then try to remove the call to that function from `/tmp/armortools-0.9/base/Sources/MainBase.hx:20`. It is used only for version info so it is safe to remove it in your clone.

**Comment by Pro-pra** [comment]
yes, install git-core pkg fix Uncaught exception Eof
Thank you!
