### ISSUE TITLE
clang 16.0.0 build fail

### ISSUE THREAD

**Issue by Pro-pra** [armory3d/armortools#1557]
I have this error on clang 16.0.0
```
In file included from ../../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/posixunit.c:4:
../../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/thread.c.h:67:2: error: call to undeclared function 'pthread_setname_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        pthread_setname_np(pthread_self(), name);
        ^
1 error generated.
```

I think need -Wno-error=implicit-function-declaration
Where in the file can it be inserted?

**Comment by luboslenco** [comment]
Try updating the Kinc submodule located at armortools/armorcore/Kinc to the latest revision available at https://github.com/Kode/Kinc. If the issue persists please report it at https://github.com/Kode/Kinc/issues.
