### ISSUE TITLE
Error not compile

### ISSUE THREAD

**Issue by maljos** [armory3d/armortools#1562]
Show error:

clang++ -std=c++17 -O2 -I../../../armorcore/v8/include -I../../../armorcore/Libraries/nfd/include -I../../../../../../usr/include/gtk-3.0 -I../../../../../../usr/include/glib-2.0 -I../../../../../../usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../../../../../usr/include/pango-1.0 -I../../../../../../usr/include/cairo -I../../../../../../usr/include/gdk-pixbuf-2.0 -I../../../../../../usr/include/atk-1.0 -I../../../../../../usr/lib64/glib-2.0/include -I../../../../../../usr/lib/glib-2.0/include -I../../../../../../usr/include/harfbuzz -I../../../armorcore/Libraries/tinydir/include -I../../../armorcore/Libraries/zlib -I../../../armorcore/Libraries/stb -I../../../armorcore/Kinc/Sources -I../../../armorcore/Kinc/Backends/System/Linux/Sources -I../../../armorcore/Kinc/Backends/System/POSIX/Sources -I../wayland -I../../../armorcore/Kinc/Backends/Graphics4/OpenGL/Sources -I../../../armorcore/Kinc/Backends/Graphics5/G5onG4/Sources -DWITH_G2 -DWITH_IRON -DWITH_ZUI -DKINC_NO_WAYLAND -DWITH_NFD -DWITH_TINYDIR -DWITH_ZLIB -DWITH_STB_IMAGE_WRITE -DIDLE_SLEEP -DKORE_G1 -DKORE_G2 -DKORE_G3 -DKORE_A1 -DKORE_A2 -DKORE_LZ4X -DKORE_OPENGL -DKINC_EGL -D_POSIX_C_SOURCE=200112L -D_XOPEN_SOURCE=600 -DKORE_G4 -DKORE_G5 -DKORE_G5ONG4 -DNDEBUG -MD -MF main.o.d -c ../../../armorcore/Sources/main.cpp -o main.o
../../../armorcore/Sources/main.cpp:1:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Build time: 0m 0s
Compilation failed.
Error: Compile error

**Comment by luboslenco** [comment]
Unable to reproduce this, sorry. Maybe helpful: https://github.com/YosysHQ/yosys/issues/681. The github action which seems to build it fine is running on Ubuntu-22.04.
