### ISSUE TITLE
Painting is slow how do i propperly troubleshoot the cause of this

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armortools#1577]
Hello when i paint on my mashine it seems to happen verry slowly and my pc makes allot of noise when it happens.
i have a 3070 and a 16 core cpu.

Is there anny way for me to c what could be causing this slowness.

I also get these mesages on launch but they seem unrelated.
```
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
Using OpenGL version 4.5 (forward-compatible).
x11 does not support getting the window position.
x11 does not support getting the window position.
Uniform W not found.
Uniform eye not found.
Uniform aspectRatio not found.
Uniform brushScale not found.
```

**Comment by luboslenco** [comment]
Hello,

- Did it work better before? Or was it always slow for you?

- Which Linux distro are you on?

- Which nvidia drivers are you using?

**Comment by NicTanghe** [comment]
Im on Rhel9 
THis is the first time i got it working on Rhel
Im using 525.105.17 Nvidia drivers
