### ISSUE TITLE
Compilation fails under windows because of error LNK2001

### ISSUE THREAD

**Issue by dsxyhw** [armory3d/armortools#1579]
**ArmorPaint version:**

[eafba11](https://github.com/armory3d/armortools/commit/eafba11ee6555750f4c9703dead512d97adaced0)

**OS/device including version:**

Windows 11 22H2
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.2.6

**Issue description:**

I followed the steps in README.md exactly, but got the following error:
1>   Creating library D:\WORK\Github\armortools\build\x64\Release\Armory.lib and object D:\WORK\Github\armortools\build\x64\Release\Armory.exp
1>v8_monolith.lib(objects.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
1>v8_monolith.lib(objects.obj) : error LNK2001: unresolved external symbol __std_find_trivial_2
1>v8_monolith.lib(heap-space.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(escape-analysis.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(load-elimination.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(zone-stats.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(runtime-test.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(sweeper.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(process-heap.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(graph.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(register-allocator.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(lazy-compile-dispatcher.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(materialized-object-store.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(marking-visitor.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(stats-collector.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(heap.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(isolate.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(log.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(sweeper.obj) : error LNK2001: unresolved external symbol __std_find_trivial_8
1>v8_monolith.lib(factory.obj) : error LNK2001: unresolved external symbol __std_count_trivial_1
1>v8_monolith.lib(wasm-objects.obj) : error LNK2001: unresolved external symbol __std_find_trivial_4
1>v8_monolith.lib(loop-analysis.obj) : error LNK2001: unresolved external symbol __std_count_trivial_8
1>D:\WORK\Github\armortools\build\x64\Release\Armory.exe : fatal error LNK1120: 6 unresolved externals
1>Done building project "Armory.vcxproj" -- FAILED.

**Steps to reproduce:**

Readme.md
Windows

# Unpack `..\armorcore\v8\libraries\win32\release\v8_monolith.7z` using 7-Zip - Extract Here (exceeds 100MB)
..\armorcore\Kinc\make --from ..\armorcore -g direct3d11
# Open generated Visual Studio project at `build\ArmorPaint.sln`
# Build and run for x64 & release

**Comment by luboslenco** [comment]
Hello, updating to the latest Visual Studio version should resolve this. https://github.com/actions/runner-images/issues/6091
