### ISSUE TITLE
Failed when trying to build in MS visual studio 

### ISSUE THREAD

**Issue by alikish4** [armory3d/armortools#1581]
ArmorPaint version: Latest build on github

OS/device including version: windows 10

*Issue description: When trying to build Armor paint in visual studio it spits 1355 Errors and wont complete.

Steps to reproduce: follow the github page exactly and get stuck when building
![image](https://github.com/armory3d/armortools/assets/136830323/8d34605c-36a4-4b6d-bd8d-8ed2f04d4d0e)
![image](https://github.com/armory3d/armortools/assets/136830323/7363a7a6-e5e6-4ea4-bf47-a661d6cf7c59)

**Comment by luboslenco** [comment]
Check https://github.com/armory3d/armortools/issues/1527.
