### ISSUE TITLE
ArmorPaint.exe Wont Launch 

### ISSUE THREAD

**Issue by alikish4** [armory3d/armortools#1582]
ArmorPaint version: latest github build

OS/device including version: win 10

Issue description: after building correctly in visual studio ArmorPaint.exe wont launch 

Steps to reproduce: build in visual studio and try to open the ArmorPaint.exe
sorry for bombarding with issues but i cant seem to figure it out :(

**Comment by luboslenco** [comment]
Please check the last readme step:
> Copy build\x64\Release\ArmorPaint.exe to build\krom to run ArmorPaint.exe directly
