### ISSUE TITLE
Slides on iPad never inactivates

### ISSUE THREAD

**Issue by lublak** [armory3d/armortools#1586]
**ArmorPaint version:**

09.23.6

**OS/device including version:**

iPad 16.5 IPad Pro 2022

**Issue description:**

If you touch any wider you always have this slider active.
Close the settings and open again. Or switching tab or interact with other guis not unfocused the slider and changes the value.

<img width="653" alt="image" src="https://github.com/armory3d/armortools/assets/44057030/c401cc2b-e3f9-4bef-a51b-db9376cc3bd9">

There is also some other weird stuff happening 

<img width="653" alt="image" src="https://github.com/armory3d/armortools/assets/44057030/17db0047-49e0-4511-9873-c7bc1ee30e52">

**Steps to reproduce:**

**Comment by lublak** [comment]
Not only the slides. If I change the color the color wheel keeps open even if I switch to some other guis.
Nothing closes xD the gui is currently complete crazy

**Comment by lublak** [comment]
<img width="1366" alt="image" src="https://github.com/armory3d/armortools/assets/44057030/e0da2268-3bec-4fd7-bc5e-108c8d9e1295">
Both sliders active plus color wheel active from color palette.
<img width="1366" alt="image" src="https://github.com/armory3d/armortools/assets/44057030/1a738105-329f-45dc-8344-f0c53201b13b">

**Comment by lublak** [comment]
And then I can not close anything

**Comment by luboslenco** [comment]
Should be resolved now in the latest update, thanks for quick report. 😀

**Comment by lublak** [comment]
@luboslenco yes its fixed :D and no problem! I am happy to test it!

**Comment by luboslenco** [comment]
Great to hear!
