### ISSUE TITLE
Rotate on object Center

### ISSUE THREAD

**Issue by lublak** [armory3d/armortools#1588]
An option to rotate on object Center not view/canvas Center.
Currently it feels uncontrollable. If you zoom pan and than rotate you object goes every where. Than you try to Center you object but if it's cantered it is somehow not cantered? I think because after rotating and than pan to move the object to the Center the view Center (canvas center) is somewhere else.

**Comment by lublak** [comment]
https://share.icloud.com/photos/01fFtpLx60zadnqUEKwu6Lzjg

**Comment by lublak** [comment]
https://github.com/armory3d/armortools/assets/44057030/40385013-746f-45b6-b60b-04c96208cffe

**Comment by melvixiodf** [comment]
Agreed, I can't paint on my mesh, every time  I rotate the viewport, my mesh moves far away into the distance, sometimes I can no longer find the mesh in the viewport, I have to start looking for it.

**Comment by luboslenco** [comment]
At `Top Menu - Camera` there is an option to switch from `Orbit` mode to `Rotate` mode. Should that be the default? Or do you have different control in mind?

**Comment by lublak** [comment]
@luboslenco Rotate mode! This is the feature. I can close this issue. So its alread included :D
Whether that should be standard or not, I don't know.
In any case, it exists. Thanks :)
