### ISSUE TITLE
Compile errors with the V8 library after running a build

### ISSUE THREAD

**Issue by Celludriel** [armory3d/armortools#1597]
I'm trying to build the project in VStudio however I'm getting following errors

![image](https://github.com/armory3d/armortools/assets/5664766/668211dc-1a9d-4da7-8d63-ec40ff28374e)

I think I have followed the right instructions to set everything up.  On stackoverflow I find following advice (https://stackoverflow.com/questions/62120533/embeding-v8-in-c-causes-unrecognized-external-symbol-errors-related-to-libcp)

However I have no idea where to add that argument since I can't find an args.gn file

(background)
I am a Java programmer that likes to experiment with other languages but I'm not a .NET professional in any way so treat me as if I don't know anything about this material

**Comment by luboslenco** [comment]
Hello, updating to the latest Visual Studio version should resolve it.

(Link with https://github.com/armory3d/armortools/issues/1579)
