### ISSUE TITLE
object is shown black when opening existing file

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1602]
**ArmorPaint version:**
v0.9 (2022-07-27) - 43f249a

**OS/device including version:**
non-DXR i guess
all specs: https://controlc.com/a4437c7a

**Issue description:**
the version of armor paint (free) is installed from aur via yay.
when i open existing project it is shown black.
the workaround is to change the viewport size, so material is updated.

https://github.com/armory3d/armortools/assets/16347074/90903400-7654-4f81-9059-3f5d81f023b5

in the paid version v0.9 (2023-07-13) - 4d0b2f5, the problem doesn't exist.

**Steps to reproduce:**
- install it from aur via yay (os - manjaro plasma)
- open existing project

**Comment by luboslenco** [comment]
Hi,

I am not familiar with aur, sorry. It looks like it does not work in the old version `2022-07-27`, but works in the new version `2023-07-13` - so I assume this is already fixed.
