### ISSUE TITLE
add to gui: 'vkrt/dxr only' to AO bake menu

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1604]
since baking ao requires vkrt build, please add this info to the gui.
something like this

![111111111111](https://github.com/armory3d/armortools/assets/16347074/e98ad16c-48c4-4759-947a-39fbf4a7d4b7)

**Comment by luboslenco** [comment]
The AO bake is supposed to work in regular builds as well. Instead of ray-tracing it's using voxels, so the quality will be a bit worse.
