### ISSUE TITLE
please add manual to gumroad files

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1605]
please add some readme or manual about vkrt build to files on gumroad.
![2023-07-29_14-48](https://github.com/armory3d/armortools/assets/16347074/56cfaa56-3c27-40d0-b716-8aa3132b0ab2)

it took me some time to realize what vkrt build is, and what is the difference (baking ao for example).

**Comment by luboslenco** [comment]
Eventually the vulkan build will be the default, but for now I recommend to just download the regular `ArmorPaint_09dev_linux64` build.
