### ISSUE TITLE
linux vkrt build crashes with segmentation fault

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1606]
**ArmorPaint version:**
it is crashing so i can't tell the version
non-vkrt build is v0.9 (2023-07-13) - 4d0b2f5 

**OS/device including version:**
all specs: https://controlc.com/a4437c7a

**Issue description:**
segmentation fault on running vkrt build.
my gpu is amd rx6700xt.
or is it nvidia only build?
or may be mesa drivers are the case?

**Steps to reproduce:**
-

**Comment by luboslenco** [comment]
Not sure on the cause, sorry. If the gpu & drivers support vulkan raytracing then it should work. Will try to eventually test on amd gpu myself but first the vkrt builds need to be updated, once https://github.com/armory3d/armortools/issues/1449 is resolved.
