### ISSUE TITLE
add version numer directly to gui

### ISSUE THREAD

**Issue by soundsbeard** [armory3d/armortools#1612]
please add version number directly to the gui
blender has it by default
![asdasd](https://github.com/armory3d/armortools/assets/16347074/f42bc02b-2ed6-4c7b-9e3b-0fa186c54030)

it is convenient, when you are watching some tutorials, you can clearly see in what version the person is working.

**Comment by luboslenco** [comment]
Added version label to the status bar, thanks for the request. https://github.com/armory3d/armortools/commit/8f5d76ca625adedab99d7159707be8a63797489f
