### ISSUE TITLE
Armorpaint Drx baking breaks

### ISSUE THREAD

**Issue by SlincHD** [armory3d/armortools#1615]
ArmorPaint.org - v0.9 (2023-07-28) - 492a0d0
Windows - Direct3D12
NVIDIA GeForce RTX 3060

![image](https://github.com/armory3d/armortools/assets/85231739/fa6cae90-1295-416e-82f3-fd8fe6bc4a04)
![image](https://github.com/armory3d/armortools/assets/85231739/eaadf586-7cbb-4978-8bcd-6666dd23d55d)
![image](https://github.com/armory3d/armortools/assets/85231739/8f12cc9b-3879-4a14-9789-71ce7b97af16)

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armortools/issues/1614, thanks for report.
