### ISSUE TITLE
Linux compile error - 'map' file not found

### ISSUE THREAD

**Issue by Cloudwolfe** [armory3d/armortools#1620]
So... I'm a newbie at Linux and I tried to build ArmorPaint from the instructions page but it failed and I don't know what to do.

- I installed Clang and the dependencies:
![Screenshot from 2023-08-15 14-20-59](https://github.com/armory3d/armortools/assets/13559182/133c954b-12de-46a2-9a3c-a582f8f7062b)

- idk if the "ubuntu clang version" is the issue here:
![Screenshot from 2023-08-15 14-35-29](https://github.com/armory3d/armortools/assets/13559182/f21ad75d-f7b3-4f7a-872f-a67e1f34af58)

- then I cloned the repo without any issues:
![Screenshot from 2023-08-15 14-46-49](https://github.com/armory3d/armortools/assets/13559182/4f32361c-bf0e-4e3c-8eb7-c519dbcd1d6b)

- but when I tried to compile it, I always got this error:
![Screenshot from 2023-08-15 14-48-20](https://github.com/armory3d/armortools/assets/13559182/d86b2625-b0c5-4462-8217-6172f518f373)
![Screenshot from 2023-08-15 14-48-29](https://github.com/armory3d/armortools/assets/13559182/7f18a24f-5c36-494d-89c9-22d732fbde3c)
![Screenshot from 2023-08-15 14-48-38](https://github.com/armory3d/armortools/assets/13559182/6d33f4d1-fa13-4276-b423-4e23f0e657a6)

**Comment by abhiraaid** [comment]
Same issue here
[compile-error.txt](https://github.com/armory3d/armortools/files/12598679/compile-error.txt)

**Comment by aditiapratama** [comment]
it's the same issue as #1562 

the solution for me is to install `sudo apt install libstdc++-12-dev` as mentioned in the comment.

**Comment by redyoshi49q** [comment]
I also ran into this issue.  Notably, `libstdc++-12-dev` is not included in [the list of dependencies for Debian-based distros](https://github.com/armory3d/armortools/wiki/Linux-Dependencies); it may be appropriate to add this package to that list.

**Comment by luboslenco** [comment]
Added `libstdc++-12-dev` to linux dependencies list now, thanks for figuring that out.
