### ISSUE TITLE
Armor Paint Shutting down when importing OBJ

### ISSUE THREAD

**Issue by DLNQNTDNTPLY** [armory3d/armortools#1624]
*ArmorPaint 0.9-600d7c7, Windows*

**Issue description:**

**Steps to reproduce:**

[handguard1committed.zip](https://github.com/armory3d/armortools/files/12476705/handguard1committed.zip)

**Comment by luboslenco** [comment]
Fixed in the 1.0alpha builds which are available now. Thanks for report!
