### ISSUE TITLE
Viewport rendering at 1/4 of its intended size on macOS

### ISSUE THREAD

**Issue by fluffy-critter** [armory3d/armortools#1626]
**ArmorPaint version:**

1.0 alpha

**OS/device including version:**

macOS 13.5.1
M1 Mac Studio
High-DPI display

**Issue description:**

The viewport only renders in the upper 1/4 of its pane and is scaled down. Tools affect it as if the viewport is filling the whole pane; for example, drawing at the midpoint of the panel applies paint to the middle of the render view.

**Steps to reproduce:**

It started out this way on first launch. Changing the UI scaling factor has no effect on the viewport size; in this screenshot the UI scale is set to 1.5x:

<img width="2672" alt="image" src="https://github.com/armory3d/armortools/assets/347162/2ec1a7e4-4850-493f-b426-9696018b5b91">

**Comment by luboslenco** [comment]
Investigating at https://github.com/Kode/Kinc/pull/805, thanks for report! Version 0.9 should work correctly in the meantime.

**Comment by luboslenco** [comment]
Should be resolved in the latest builds.

**Comment by fluffy-critter** [comment]
Was just able to verify that it's fixed. Thanks!
