### ISSUE TITLE
Linux Vulkan compilation fails

### ISSUE THREAD

**Issue by ColumbusUtrigas** [armory3d/armortools#1629]
**ArmorPaint version: e8b7d18c57c82d02c9b76d6618e8837473b08737 or tags/23.08**

**OS/device including version: Arch Linux, GTX1660Ti, 535.86.05**

**Issue description: **

Compiling with Vulkan backend, these errors are thrown

../../../armorcore/Sources/main.cpp:3681:3: error: no matching function for call to 'kinc_raytrace_acceleration_structure_init'
                kinc_raytrace_acceleration_structure_init(&accel, &commandList, vertex_buffer, index_buffer, scale);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../armorcore/Kinc/Sources/kinc/graphics5/raytrace.h:37:16: note: candidate function not viable: requires 4 arguments, but 5 were provided
KINC_FUNC void kinc_raytrace_acceleration_structure_init(kinc_raytrace_acceleration_structure_t *accel, struct kinc_g5_command_list *command_list,
               ^
../../../armorcore/Sources/main.cpp:3726:3: error: use of undeclared identifier 'kinc_raytrace_set_textures'
                kinc_raytrace_set_textures(&texpaint0->impl._renderTarget, &texpaint1->impl._renderTarget, &texpaint2->impl._renderTarget, &texenv->impl._texture, &texsobol->impl._texture, &texscramble->impl._texture, &texrank->impl._texture);
                ^
../../../armorcore/Sources/main.cpp:3747:3: error: no matching function for call to 'kinc_raytrace_set_target'
                kinc_raytrace_set_target(&render_target->impl._renderTarget);
                ^~~~~~~~~~~~~~~~~~~~~~~~
../../../armorcore/Kinc/Sources/kinc/graphics5/raytrace.h:43:16: note: candidate function not viable: no known conversion from 'kinc_g5_render_target_t *' (aka 'kinc_g5_render_target *') to 'struct kinc_g5_texture *' for 1st argument
KINC_FUNC void kinc_raytrace_set_target(struct kinc_g5_texture *output);

**Steps to reproduce:**

`../armorcore/Kinc/make --from ../armorcore -g vulkan --compiler clang --compile`

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armortools/issues/1449.
