### ISSUE TITLE
Cloud connection error

### ISSUE THREAD

**Issue by ColumbusUtrigas** [armory3d/armortools#1630]
**ArmorPaint version: e8b7d18c57c82d02c9b76d6618e8837473b08737**

**OS/device including version: Arch Linux, GTX1660Ti, 535.86.05**

I have a custom DNS server for a local network, which falls back to 8.8.8.8 for external connections.

**Issue description:**

Error while opening cloud folder.

--2023-09-10 14:01:40--  https://armorpaint.fra1.digitaloceanspaces.com/?list-type=2
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving armorpaint.fra1.digitaloceanspaces.com (armorpaint.fra1.digitaloceanspaces.com)... 5.101.109.44
Connecting to armorpaint.fra1.digitaloceanspaces.com (armorpaint.fra1.digitaloceanspaces.com)|5.101.109.44|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: ‘../../armorpaint/build/krom/./data//download.bin’

../../armorpaint/build/krom/./data//download.bin            [ <=>                                        ] 270.98K  --.-KB/s    in 0.1s

2023-09-10 14:01:41 (2.08 MB/s) - ‘../../armorpaint/build/krom/./data//download.bin’ saved [277479]

Sources/arm/Console.hx:46: Error: Check internet connection to access the cloud

**Steps to reproduce:**
1. Click on "Cloud" button in the browser tab
2. See the error

**Comment by abhiraaid** [comment]
My cloud is not loading as well. 
on Pop!_OS 22.04

**Comment by mikerodd** [comment]
same issue here in ubuntu 22.04

**Comment by StrandedAlien** [comment]
Same under Manjaro. But at least no hard hangup like in previous versions. 

arm/Console.hx:69: Error: Check internet connection to access the cloud

**Comment by WhitleyStriber** [comment]
Cloud also not loading as well. Arch Linux on a Thinkpad. Git build from today. Nothing shows up in console but I get a red "Error: Check internet connection to access the cloud" error message in ArmorPaint.

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armortools/issues/1654, thanks for reports.
