### ISSUE TITLE
Instulation problem

### ISSUE THREAD

**Issue by Stormriderplayz** [armory3d/armortools#1632]
I'm having with the last thing to do on step 1 of building ArmorPaint, Powershell says that it can't find the module. I would like to know how to solve this problem.
The tutorial I used is here: https://gist.github.com/lenicyl/804786c928c6e97fa25c23836e2b06b3
![Screenshot (3952)](https://github.com/armory3d/armortools/assets/112338323/90e0ab70-f2de-4d44-a6a5-3ea49a543eb2)

**Comment by luboslenco** [comment]
Hi. please see up to date build instructions here: https://github.com/armory3d/armortools/blob/main/armorpaint/README.md.

**Comment by Stormriderplayz** [comment]
I'm trying to follow the instructions but it says that the armortools already exist and the next step says that it can't find the path. You see I succeded in the steps from the other instruction but failed on the last step, mabye what I did before is messing it up somehow if so how can i remove it? Can I just delete the folder?

Also thank you for your responce I'll continue trying.

**Comment by Stormriderplayz** [comment]
I almost forgot should I just do the Windows instructions or should I do the one top first?
