### ISSUE TITLE
Everything is too large on MacOS

### ISSUE THREAD

**Issue by bioxoid** [armory3d/armortools#1635]
**ArmorPaint version:**

1.0 alpha

**OS/device including version:**

macOS 13.5.1
M1 Mac
Retina Display

**Issue description:**
Fonts and Icons are so large, I'm not sure whether this is right size or not but it's frustrating.
And viewport is also rendering at 1/4 as well as other issue.

**Steps to reproduce:**
Compiled from the source.

<img width="1440" alt="Screenshot 2023-09-18 at 06 16 26" src="https://github.com/armory3d/armortools/assets/86451343/dab5bd55-a550-4aae-8066-f2f28cf3cf6c">

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/armory3d/armortools/issues/1626.

**Comment by luboslenco** [comment]
> Fonts and Icons are so large,

Try lowering the `Preferences... - Interface - UI Scale` slider.

> And viewport is also rendering at 1/4

Should be resolved now.
