### ISSUE TITLE
How do I reset the UI scale?

### ISSUE THREAD

**Issue by NicCrimson** [armory3d/armortools#1638]
I accidentally entered a large value and now everything is huge and I can't reset the value to normal.

**Comment by MathemanFlo** [comment]
The issue is easy to solve

1. open ArmorPaint's directory
2. go to `data `directory
3. Open `config.json`
4. Edit the entry `window_scale`, set it back to 1

![grafik](https://github.com/armory3d/armortools/assets/28649121/99cf01fa-0f9b-4582-9d64-d5b51d48861d)

**Comment by NicCrimson** [comment]
That Kind of worked but I still can't see anything
![image](https://github.com/armory3d/armortools/assets/72427419/f8a79e7a-1eec-4058-9b26-cda58330ffba)

**Comment by NicCrimson** [comment]
I solved it, deleted the config file.

**Comment by MathemanFlo** [comment]
The reason is that you probably also changed the panel sizes (like the pane on the right). Deleting the config lets ArmorPaint create a new one on startup.
