### ISSUE TITLE
Viewport only takes up 1/4 of the viewport space – on Mac M1 / Ventura

### ISSUE THREAD

**Issue by MarkV9git** [armory3d/armortools#1643]
**ArmorPaint version:**

ArmorPaint_10alpha_apple_silicon

**OS/device including version:**

MacOS: Ventura 13.5.2, MacBookPro18,2 M1 Max, 16', 2021

Apple M1 Max:

  Chipsatz-Modell:	Apple M1 Max
  Typ:	GPU
  Bus:	Integriert
  Gesamtanzahl der Kerne:	32
  Hersteller:	Apple (0x106b)
  Metal-Unterstützung:	Metal 3

**Issue description:**

The viewport only takes up 1/4 of the viewport (screens attached).

**Steps to reproduce:**

![viewport-ArmorPaint_10alpha_apple_silicon-Mac-Ventura-13 5 2-splitview](https://github.com/armory3d/armortools/assets/143900775/cbd7a909-eecb-4c9a-b427-d2e12f3da59c)
![viewport-ArmorPaint_10alpha_apple_silicon-Mac-Ventura-13 5 2](https://github.com/armory3d/armortools/assets/143900775/8cbd1e8a-a526-4418-a707-c10d3e5fb156)

**Comment by luboslenco** [comment]
Hello. Is this still an issue in the latest 1.0alpha build? It should be fixed already.

**Comment by MarkV9git** [comment]
Hello, it seems to be working fine now.
thx Markus

**Comment by luboslenco** [comment]
Awesome! Thanks for letting me know.
