### ISSUE TITLE
Linux build error - clang 16

### ISSUE THREAD

**Issue by tincup7** [armory3d/armortools#1646]
**ArmorLab version:**

Armorlab [91f3f3c]

**OS/device including version:**

AMD Ryzen Threadripper 3970X 32-Core Processor,  AMD Radeon Pro W6600, 64 GB ram, Endeavoros, kernel 6.5.7-arch1-1 (64 bit)

**Package:**
clang 16.0.6-1
    C language family frontend for LLVM

compiler-rt 16.0.6-2
    Compiler runtime libraries for clang

rocm-clang-ocl 5.6.1-1
    OpenCL compilation with clang compiler

rocm-llvm 5.6.1-1
    Radeon Open Compute - LLVM toolchain (llvm, clang, lld)

**Issue description:**

`In file included from ../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/posixunit.c:4:
../../armorcore/Kinc/Backends/System/POSIX/Sources/kinc/backend/thread.c.h:68:2: error: call to undeclared function 'pthread_setname_np'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        pthread_setname_np(pthread_self(), name);
        ^
1 error generated.
make: *** [makefile:65: posixunit.o] Error 1
`

**Steps to reproduce:**

`armorcore/Kinc/make --from armorcore -g opengl --compiler clang --compile`

**Comment by luboslenco** [comment]
Merging with https://github.com/armory3d/armortools/issues/1671. Thanks for report.
