### ISSUE TITLE
Armorpaint not updated through armorLab

### ISSUE THREAD

**Issue by NicTanghe** [armory3d/armortools#1653]
Hello i bought armorlab . armorpaint.

I decided to update to 1.0 but the gumroad seems to have only been updated for armorpaint.

armorlab:
![image](https://github.com/armory3d/armorcore/assets/13624265/c0f28707-fa1e-4f73-8e82-7e1b84efbddd)

someone else`s armorpaint download tab looks like this :

![image](https://cdn.discordapp.com/attachments/486774102296625171/1171067412301492244/image0.jpg?ex=655b5484&is=6548df84&hm=b523e591838198cb62f4fbf56bbf9038aab63fe2a18c0bde103462ac810d3657&)

**Comment by luboslenco** [comment]
Hello, apologizes for the delay and thanks for your support. I recommend the 0.9 version as the latest "stable" build, while the 1.0alpha is in development. But if you want the 1.0alpha please just send me [an email](https://armorpaint.org/community) and I will send the armorpaint key back.

**Comment by NicTanghe** [comment]
Hej i think i sent an emain and didn`t get a reply.
Also the extra folder is gone these days so also no old version.

I will send another email.
