### ISSUE TITLE
Armor Paint and Armor Lab not loading material in cloud

### ISSUE THREAD

**Issue by SupersonicLemon** [armory3d/armortools#1654]
Hi, I downloaded Armor Paint 10_alpha and Armor Lab 01 for Apple silicon on Mac OS Ventura, but when I go to Browse---Cloud, I always have the same error:"Error: Check internet connection to access the cloud". What can I do?

**Comment by WhitleyStriber** [comment]
Also having the same issue. Arch Linux on a Thinkpad though.

**Comment by luboslenco** [comment]
Investigating together with https://github.com/armory3d/armortools/issues/1668, thanks for report.
