### ISSUE TITLE
Crash on opening nodes

### ISSUE THREAD

**Issue by jackee03** [armory3d/armortools#1657]
*ArmorPaint 1.0 alpha-c253912, Windows*

Crash when attempting to open nodes 

Steps: open Armor paint, press nodes

**Comment by MentalBase** [comment]
![image](https://github.com/armory3d/armortools/assets/69431567/7fe88e34-eadb-4e4e-9ee7-a2ac903d1ad8)
I confirm. Even when you try to open it inside other nodes.

**Comment by luboslenco** [comment]
Should be resolved, thanks for report.
