### ISSUE TITLE
ArmorLab Compling Error - unresolved external symbol OrtGetApiBase & OrtSessionOptionsAppendExecutionProvider_DML

### ISSUE THREAD

**Issue by AstralForesight** [armory3d/armortools#1661]
**ArmorLab version:**
Commit 7c4cfbab3d41e0cf47d82e0d216c3f6b1dee99d2 as of 12/6/2023 4:53 PM GMT

**OS/device including version:**
OS: Windows 10
GPU: RTX 3060 12Gb 
(Likely not needed outside of it being Windows 10)

**Issue description:**
Build error with I believe onnx; two "Unresolved external symbol" errors
(Please excuse wrong wording or attribution I am not exactly code savvy yet)

After successfully building and running ArmorPaint on this commit, all steps on the ArmorLab Readme go smoothly until "# Build and run for x64 & release". 

VS Throws these on the console with "fatal error":
(file paths shortened):
```
...
1>Creating library armortools\armorlab\build\x64\Release\ArmorLab.lib and object armortools\armorlab\build\x64\Release\ArmorLab.exp
1>main.obj : error LNK2001: unresolved external symbol OrtGetApiBase
1>main.obj : error LNK2001: unresolved external symbol OrtSessionOptionsAppendExecutionProvider_DML
1>armortools\armorlab\build\x64\Release\ArmorLab.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "ArmorLab.vcxproj" -- FAILED.
```

Redid the process _fresh_, clean folders and such, from git pulling Armortools onward, with no success 3 times so far (one last time before hitting Submit), and have moved the onnx/win32 & onnx/include files to different places in the file tree that would seem to make sense to try and make sure I was covering my bases for user error and if there was an error in the steps (though that's probably just my current coding ignorance playing out)

**Steps to reproduce:**
Follow steps outlined in ArmorLab Readme with a Windows 10 system on the 7c4cfbab3d41e0cf47d82e0d216c3f6b1dee99d2 commit

-- Okay, hope I did this right ^^ --

**Comment by Zoko-Std** [comment]
Exact same error here.

**Comment by JackD83** [comment]
You can add 
"..\onnx\win32\onnxruntime.lib"
as additional input in the linker settings of the project.

 It builds successfully, but I still can not run it after copying everything to the build/krom folder. The exe fails without error.

**Comment by RoxDevvv** [comment]
i fix that by downloading directml + onnx runtime

![image](https://github.com/armory3d/armortools/assets/51464152/b21a809a-ba3f-4e4d-9bef-3aea9c7f70bf)
![image](https://github.com/armory3d/armortools/assets/51464152/d2653a4f-d12e-440f-bbcf-4cabafd7445a)

the build succeeds however the produced exe is broken clicking on it doesn't show anything as previous guy said above me The exe fails without error.

**Comment by luboslenco** [comment]
Will investigate together with https://github.com/armory3d/armortools/issues/1664.
