### ISSUE TITLE
ArmorLab Compling Error

### ISSUE THREAD

**Issue by Justspeeding** [armory3d/armortools#1662]
**ArmorLab version:[armorcore @ 0351f7e](https://github.com/armory3d/armorcore/tree/0351f7e9eabf8b4b4eb5c8072109be4e7ee46769)

**OS/device including version:*win 11*

**Issue description:**
..\armorcore\Kinc\make --from ..\armorcore -g direct3d11 then i get the below error

**Steps to reproduce:**

![2023-12-13 13 53 39](https://github.com/armory3d/armortools/assets/12138145/38733c3a-7f9e-4031-b1ab-20977b432537)

**Comment by luboslenco** [comment]
Will investigate together with https://github.com/armory3d/armortools/issues/1664.
