### ISSUE TITLE
All plugins fail to load due to TypeError: arm.Plugin is not a constructor

### ISSUE THREAD

**Issue by RobotRoss** [armory3d/armortools#1663]
**ArmorPaint version:**
ArmorPaint #23dcc34

**OS/device including version:**
`             .',;::::;,'.                crystalyne@hortonator 
         .';:cccccccccccc:;,.            --------------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 39 (Workstation Editi 
    .:cccccccccccccccccccccccccc:.       Kernel: 6.6.7-200.fc39.x86_64 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Uptime: 2 hours, 4 mins 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Packages: 2574 (rpm), 72 (flatpak) 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Shell: bash 5.2.21 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Resolution: 3840x2160 
:cccccccccccccc;MMM.;cccccccccccccccc:   DE: GNOME 45.2 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   WM: Mutter 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM Theme: Adwaita 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: ZorinGreen-Dark [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: gnome-terminal 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Ryzen 7 5800X3D (16) @ 3.400G 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: AMD ATI Radeon RX 6800/6800 XT /  
:cccccccccccccccccccccccccccc:'.         Memory: 15291MiB / 31995MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
                                                                 

`

**Issue description:**
Upon attempting to enable any plugin, plugin will fail to load and will spit out console error:
`TypeError: arm.Plugin is not a constructor`

**Steps to reproduce:**
Attempt to enable any plugin.

**Comment by luboslenco** [comment]
Should be resolved, thanks for report.
