### ISSUE TITLE
Linux error compilation (ArmorPaint and ArmorLab too)

### ISSUE THREAD

**Issue by cosM-green** [armory3d/armortools#1673]
**ArmorPaint version:**
Github repository

**OS/device including version:**
Linux Mint 21.3, Nvidia RTX 2070 Super, nvidia-driver-535

**Issue description:**
make: *** [makefile:8: ArmorPaint] Error 1
Build time: 0m 10s
Compilation failed.
Error: Compile error

**Steps to reproduce:**
Compile on Linux

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armortools/issues/1671.
