### ISSUE TITLE
ArmorLab Crashes On Start

### ISSUE THREAD

**Issue by TKyleB** [armory3d/armortools#1674]
**ArmorPaint version:**
[armorcore @ 8d713aa](https://github.com/armory3d/armorcore/tree/8d713aa5794f4f30c9c9dac9806478058019ac8d)

**OS/device including version:**
RTX 4080
Windows 11

**Issue description:**
Upon launching ArmorLab.exe the program immediately crashes.
A kinc.dmp file is generated in the same directory.
[kinc.dmp](https://github.com/armory3d/armortools/files/14077360/kinc.dmp)

**Comment by luboslenco** [comment]
Will look into it together with issues linked at https://github.com/armory3d/armortools/issues/1664.
