### ISSUE TITLE
Message when starting ArmorLab that the library libonnxruntime.so.1.14.1 is missing, although it exists

### ISSUE THREAD

**Issue by cosM-green** [armory3d/armortools#1675]
**ArmorLab version:**
Github build

**OS/device including version:**
Linux Mint 21.3, Nvidia RTX 2070 Super, nvidia-driver-535

**Issue description:**

./ArmorLab: error while loading shared libraries: libonnxruntime.so.1.14.1: cannot open shared object file: No such file or directory

**Steps to reproduce:**
Last step of tutorial ArmorLab compiling on Linux, when need to launch program from console

**Comment by curVV** [comment]
You can try running with `LD_LIBRARY_PATH=../../armorlab/build/krom ./ArmorLab ../../armorlab/build/krom`
