### ISSUE TITLE
ArmorPaint built successfully but won't run W10

### ISSUE THREAD

**Issue by bruno-tab** [armory3d/armortools#1676]
Thank you for working on ArmorPaint!
I've followed along to the tutorial in the readme and all went well (1 succeeded, 0 failed/up-to-date/skipped) but when trying to open ArmorPaint.exe (copied and pasted into build/Krom) the cursor changes to loading briefly but nothing happens - except a memory dump is created which when opened in VS reads: 
Exception code 0x80000003
A breakpoint was encountered
Heap/error information not present/blank
Googling this didn't help. Any help would be appreciated

VS 22, Windows 10.0.19045, Nvidia GTX 660 Ti

**Comment by bruno-tab** [comment]
I should have mentioned the first time I tried to build, I was using VS19 which failed,  then later it worked with VS22. A Google result says this could be due to "Windows registry mix-up that leftover keys of uninstalled applications could trigger".

**Comment by luboslenco** [comment]
Thanks for report! Fix coming soon together with issues linked at https://github.com/armory3d/armortools/issues/1671.
