### ISSUE TITLE
ArmorPaint.exe producing memory dump with exception code 0x80000003: "A breakpoint was encountered." when run

### ISSUE THREAD

**Issue by M-Aronnax** [armory3d/armortools#1678]
ArmorPaint v0.9
Microsoft Windows 11 Pro Version	10.0.22621 Build 22621
Built using Microsoft Visual Studio Community 2022

After building ArmorPaint.sln and moving ArmorPaint.exe to C:\Users\[user]\armortools\armorpaint\build\krom, running ArmorPaint.exe did nothing. Upon running it the second time it makes a memory dump in the same directory with an exception code 0x80000003: "A breakpoint was encountered". Not sure what is causing this exactly.

Strangely, pinning ArmorPaint.exe to taskbar and spam clicking it enough will actually get it to open.

Not sure if this is a problem with my OS or with the application itself. I've already tried disabling startup apps, running the system file checker and DISM tools, checking my hard drive with CHKDSK, updating windows and restarting the entire compilation + build process for ArmorPaint, but still no luck.

**Steps to reproduce:**
1. Follow the steps to build the ArmorPaint app from source on windows as listed [here.](https://github.com/armory3d/armortools/tree/main/armorpaint) I 

2. Pin ArmorPaint.exe to taskbar and click it repeatedly until it opens

**Comment by luboslenco** [comment]
Will investigate together with https://github.com/armory3d/armortools/issues/1671, thanks for additional info!

**Comment by SiKo117** [comment]
@luboslenco Thank You very much for responding quickly.

@M-Aronnax thanks for the info, using your method I can open the program so I created the bat script to run the program multiple times but I didn't check it, if the program is running or not running perfectly. The bat script is down below just in case someone wanna try. Just change the variables according to the use.

@echo off
set "exe=ArmorPaint.exe"
set "wait_time=0.1"
set "max_runs=32"
set /a "counter=0"

:loop
if %counter% lss %max_runs% (
    start "" "%exe%"
    timeout /t %wait_time% /nobreak >nul
    set /a "counter=counter+1"
    goto loop
)
