### ISSUE TITLE
ArmorPaint is not loading (Win)

### ISSUE THREAD

**Issue by cosM-green** [armory3d/armortools#1680]
**ArmorPaint version:**
Github build

**OS/device including version:**
Windows 10 22H2

**Issue description:**
ArmorPaint does not start, although the cursor shows that there is a loading. All assembly points were completed correctly.

**Steps to reproduce:**
Compile for Win

**Comment by SiKo117** [comment]
Having the same issue putting my dmp file summery image in it too

![image](https://github.com/armory3d/armortools/assets/78236248/382d187e-9580-4950-bb91-4dea6734341b)

**Comment by luboslenco** [comment]
Will get to it as soon as I get to my windows machine, linking to https://github.com/armory3d/armortools/issues/1671.
