### ISSUE TITLE
Any good Guide to compile Android version of the Program?

### ISSUE THREAD

**Issue by SiKo117** [armory3d/armortools#1683]
Hello Thanks in advance,

Does anyone know a good guide to compile the Android version of the Program Because i constantly facing multiple errors like not able to apply the patch and after that v8 library missing or something wrong.
Please help

**Comment by luboslenco** [comment]
Sorry not yet, and right now have to focus on https://github.com/armory3d/armortools/issues/1671. But still hoping to make android build process smooth in the coming updates!

**Comment by SiKo117** [comment]
@luboslenco Its fine bro, Thank you very much for creating this amazing application. Really looking forward for this. LOVE From INDIA.❤

**Comment by luboslenco** [comment]
Thanks a lot, great to hear!
