### ISSUE TITLE
ArmorPaint Run Error

### ISSUE THREAD

**Issue by PickleKid07** [armory3d/armortools#1684]
ArmorPaint version: 1.0 alpha

OS/device including version: Windows 10 

Issue description: The source code builds fine with no errors, but when I copy the ArmorPaint.exe file into the build/krom folder it doesn't run, and produces a kinc.dmp file. The contents of the .dmp file is below.

![image](https://github.com/armory3d/armortools/assets/159088738/fdd322e1-c676-4374-8a97-f33df36f7489)

**Comment by luboslenco** [comment]
Fix incoming with https://github.com/armory3d/armortools/issues/1671.
