### ISSUE TITLE
Cannot run armorpaint.exe after compiling it. Build was fine.

### ISSUE THREAD

**Issue by throbbingmoist** [armory3d/armortools#1685]
Win11, AMD CPU, Nvidia Notebook GPU, VS 2022 with all the dependencies I'm aware of.
[kinc.dmp](https://github.com/armory3d/armortools/files/14176545/kinc.dmp)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armortools/issues/1671, thanks for report.
