### ISSUE TITLE
Could not installed armorpaint in Fedora 38

### ISSUE THREAD

**Issue by md-fahad-ali** [armory3d/armortools#1687]
In this doc https://github.com/armory3d/armortools/tree/main/armorpaint I have do same things I have compiled and it shows me done 
But there is some issue that I have found 
strip ArmorPaint 
strip: 'ArmorPaint': No such file
How to resolve that issue

**Comment by luboslenco** [comment]
Hi, please try searching through existing issues, ie. https://github.com/armory3d/armortools/issues/1398 might help.

**Comment by md-fahad-ali** [comment]
Hello I compiled it and it was showing me done but I cant set strip ArmorPaint it doesn't work 
how to solve this one though I might be dumb I didn't find any this type issue which help me to figure out
