### ISSUE TITLE
Unresolved external symbol for OrtGetApiBase & OrtSessionOptionsAppendExecutionProvider_DML

### ISSUE THREAD

**Issue by MetalHunterR** [armory3d/armortools#1688]
**ArmorPaint version:**
Commit: [b658b62](https://github.com/armory3d/armortools/commit/b658b626a24eb7fe13330c8526f794555547dc19)

**OS/device including version:**
OS: Windows 11 Pro Version 10.0.22631 Build 22631
GPU: GTX 1660 Ti 6Gb

**Issue description:**
Following the steps provided on GitHub, but build failed, can't find onnx. 

```
0>main.obj: Error LNK2001 : unresolved external symbol OrtGetApiBase
0>main.obj: Error LNK2001 : unresolved external symbol OrtSessionOptionsAppendExecutionProvider_DML
0>ArmorLab.exe: Error LNK1120 fatal: 2 unresolved externals
0>------- Finished building project: ArmorLab. Succeeded: False. Errors: 3. Warnings: 0
```

**Steps to reproduce:**
Follow the steps of the readme, and when you reach the build stage, you will find it

**Comment by luboslenco** [comment]
Will try to fix soon at https://github.com/armory3d/armortools/issues/1664, thanks for report.
