### ISSUE TITLE
macOS - Could not load krom.js, aborting.

### ISSUE THREAD

**Issue by Athomield** [armory3d/armortools#1690]
I did exactly like the readme (armorpaint) file, I even took the executable from the build process (which exists in an Xcode folder) and still same error 

![Screenshot 2024-02-14 at 2 15 05 AM](https://github.com/armory3d/armortools/assets/7095418/f9b3720c-a569-4e70-b634-16ff68dbac4e)

**Comment by luboslenco** [comment]
Will fix together with https://github.com/armory3d/armortools/issues/1671, thanks for report.

(link with https://github.com/armory3d/armortools/issues/1450 https://github.com/armory3d/armortools/issues/1665)
