### ISSUE TITLE
I get errors with building the project (Freshly Downloaded) on WIndows 10

### ISSUE THREAD

**Issue by xavier114** [armory3d/armortools#1700]
**ArmorPaint version:**
Latest

**OS / GPU model:**
Windows 10 / Nvidia RTX 4060

**Issue description:**
![image](https://github.com/armory3d/armortools/assets/46450797/d9355674-cb13-4d2a-90a6-54fb3caa3edc)

**Comment by luboslenco** [comment]
Will fix soon together with https://github.com/armory3d/armortools/issues/1664, thanks for report.
