### ISSUE TITLE
Segmentation Fault when opening some cloud folders

### ISSUE THREAD

**Issue by RedAuburn** [armory3d/armortools#1759]
**ArmorPaint version:**
[91621cd](https://github.com/armory3d/armortools/commit/91621cd8d8fb8507870660ff7637e399eae84d14)

**OS / GPU model:**
Fedora 40
1080 Ti

**Issue description:**
trying to open the cloud materials folder causes a segmentation fault

**Steps to reproduce:**
1. run armorpaint
2. open the browser tab
3. open the cloud assets
4. open the materials folder
5. double click on the armorlab folder

**Comment by luboslenco** [comment]
Should be resolved, thanks for report!
