### ISSUE TITLE
Suggest new icons

### ISSUE THREAD

**Issue by lydex256** [armory3d/armortools#1770]
Hello, I want to suggest new icons for developing programs "ArmorForge" and "ArmorSculpt".
They are free for all targets, and no need for indicate authorship :)
![ArmorForge](https://github.com/user-attachments/assets/5e963658-7b36-4beb-97d3-42f61e6bc610)
![ArmorSculpt](https://github.com/user-attachments/assets/7a0f86d9-bbe6-4e13-be4c-e219dc4bcadc)

I hope, that my idea will contribute to the development of Armory :D

**Comment by luboslenco** [comment]
Super cool, thanks a lot! Added at https://github.com/armory3d/armortools/commit/8a1cb158cd3117a7e467f240087dd85104a12c7f. Any chance to also create the letter "P"? :smiley:

**Comment by lydex256** [comment]
> Super cool, thanks a lot! Added at [8a1cb15](https://github.com/armory3d/armortools/commit/8a1cb158cd3117a7e467f240087dd85104a12c7f). Any chance to also create the letter "P"? 😃

Oh, big thanks for applying my creations <3.
What about the new icon with the letter "P": yes of course, i can try draw it at these days, and send with reply under this issue :D

**Comment by lydex256** [comment]
@luboslenco 
I've returned😄 
While I was making the icon, I was saving some versions that could have been used, and I just left them.
There are two variants with saving "Armory" style (variance in alignment):
![ArmorPLetter](https://github.com/user-attachments/assets/65ee2862-4c34-40fd-a119-2a99320e1aac)
![ArmorP](https://github.com/user-attachments/assets/1f6f93f1-5711-42d9-8798-60b763fa1b11)
And new icon with redrawing:
![ArmorPNewStyle](https://github.com/user-attachments/assets/1495c07b-2167-498b-929f-77cc96048c11)
I couldn't decide on a choice, so I'm leaving it to you🤔

**Comment by luboslenco** [comment]
Wow, thanks again! Still thinking which one to choose. :) I also tried another variant by using your "F" logo.

![cc](https://github.com/user-attachments/assets/a91a1128-6cc4-4fee-abc7-815b32627a2b)

**Comment by lydex256** [comment]
> Wow, thanks again! Still thinking which one to choose. :) I also tried another variant by using your "F" logo.
> 
> ![cc](https://private-user-images.githubusercontent.com/3685704/378093434-a91a1128-6cc4-4fee-abc7-815b32627a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNDk2NjYsIm5iZiI6MTcyOTM0OTM2NiwicGF0aCI6Ii8zNjg1NzA0LzM3ODA5MzQzNC1hOTFhMTEyOC02Y2M0LTRmZWUtYWJjNy04MTViMzI2MjdhMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTlUMTQ0OTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE0MTI3Mjg4M2YzNzI4N2UyM2YyZWI2NTY5YmMxOWEzY2Q5MjgwNjVhYWU4NGQ2ZWUzMDdiMWIyMWQ4MjUxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tOpkLo0oPGdksnSeSfXZ4hRycc1SuNLUUlsZ5MeQLi0)

Heh, it looks very interesting :D
But I saw your version a little different for me: this letter like a spiral system (for example: my letter "S"): added stripe is located under the top line of "F", and takes color from bottom line of this letter, and that, in turn, takes an even darker color.
But your design stylish too😃

**Comment by luboslenco** [comment]
> But I saw your version a little different for me: this letter like a spiral system (for example: my letter "S"): added stripe is located under the top line of "F", and takes color from bottom line of this letter, and that, in turn, takes an even darker color.

Sounds like a great idea!
