### ISSUE TITLE
Why are you scamming people?

### ISSUE THREAD

**Issue by HyperAlch** [armory3d/armortools#1773]
People that have payed money for your ArmorPaint software are complaining in your discord about the software being unusable for many people. Yet you have ignored them and have yet to patch the issues. If half your community can't even use the software, why do you keep selling it?

Stop scamming people. Either take the product down from stores or fix it. You people make me sick. You're are actually sub-human.

**Comment by DENG-XC** [comment]
Hi, I am considering purchasing this application. Could you explain what problems you have faced?

**Comment by AnanasikDev** [comment]
@DENG-XC you could try build it yourself, try it, and then pay if you find it worth it btw.

**Comment by HyperAlch** [comment]
@DENG-XC 
> Hi, I am considering purchasing this application. Could you explain what problems you have faced?

For me it just doesn't start unless I go back a couple versions. Even then it is extremely unstable. I would encourage you to look in the "armorpaint" channel in their discord and just scroll through the messages. A lot of people are having major issues and I've seen quite a few messages that admit the straight up regret buying it. 

If you want to build it from source like @AnanasikDev says, that is up to you. I personally don't have time for that BS, hence why I paid. However, in the state that the project is in, there is NO excuse to lock pre-compiled binaries behind a pay wall. It's actually gross. 

If in a couple years the program becomes stable and then they want to essentially sell binaries, I'm fine with that. But right now you are essentially paying to test their buggy software, unless you compile from source.

**Comment by luboslenco** [comment]
As stated on the website, there is a no questions asked refund policy. Anyone having an issue please just send me an email to get a full refund.

The website also has a disclaimer "The alpha version has many rough edges and the experience may be frustrating.". Purchase the pre-built binaries only if you want to support further development.

Alternatively, you can also build from source if you like like already mentioned. I try to work on the software here in the open so anyone can have access to the source code or submit bug reports. The software still has ways to go, and I am planning to continue working on it and keep releasing updates. Every issue report or feature request helps.

I am copy-pasting the original message below - for anyone stumbling upon this, feel free to judge the human character yourself.

> People that have payed money for your ArmorPaint software are complaining in your discord about the software being unusable for many people. Yet you have ignored them and have yet to patch the issues. If half your community can't even use the software, why do you keep selling it?

> Stop scamming people. Either take the product down from stores or fix it. You people make me sick. You're are actually sub-human.

**Comment by HyperAlch** [comment]
> As stated on the website, there is a no questions asked refund policy. Anyone having an issue please just send me an email to get a full refund.

Been trying to get a refund from Itch.io for 3 days now, not exactly working out. But sure, what's your email?

> The website also has a disclaimer "The alpha version has many rough edges and the experience may be frustrating.". Purchase the pre-built binaries only if you want to support further development.

It wasn't just the 1.0 alpha build that I and others are having issue with, as I stated. But feel free to ignore that part for your own benefit.

> Alternatively, you can also build from source if you like like already mentioned. 

Yeah, I could. But you could also just give away the binaries for free until the program is in a state that justifies taking money from people. You can hide behind this "build from source" point if you want, but you know that most people don't have the time to build every single update from source. And I know that you know this, because if it was that fast and easy why lock the binaries behind a paywall at all? Just take normal donations at that point.

> The software still has ways to go, and I am planning to continue working on it and keep releasing updates. Every issue report or feature request helps.

Cool, then take simple donations and stop locking broken binaries behind a paywall. It sucks to pay for something with clear strings attached (the binaries) then immediately get a borked program from the download page hidden behind a paywall.

> I am copy-pasting the original message below - for anyone stumbling upon this, feel free to judge the human character yourself.

Oh? Judgement of human character? Really? Do you know how it feels to live below the USA poverty line and use the last $20 of expendable cash (money not for rent, food, utilities, etc) to buy a program for your side project that you can only work on 2 hours a day, and you just get handed a pile of crap? I am willing to pay for an open source program to save compilation time on my 2 hour a day time limit. I am not willing to follow a giant, official "add to cart" section on your website clearly communicating that the program is in a purchasable state as long as you don't use the alpha build. Is that the "human character" your talking about. Really? Who is actually the bad guy here? The one doing the manipulating, or the one upset about being manipulated. Holy narcissism.

**Comment by HyperAlch** [comment]
![image](https://github.com/user-attachments/assets/24bfed85-c518-4362-aece-7a73108b2e27)

@luboslenco 

# What about this screams "The program isn't in a stable state, even the non-alpha build, but donated if you want to help developed"

## Actually sickening

**Comment by todirbg** [comment]
Kid you going to learn that nothing is free in life and no one is obligated to give you anything for free. You pay with money or you pay with time and at the end it is the same thing.

**Comment by HyperAlch** [comment]
@todirbg 

> Kid you going to learn that nothing is free in life and no one is obligated to give you anything for free. You pay with money or you pay with time and at the end it is the same thing.

You should really learn to read the whole conversation instead of just reading the title and commenting based on that. How does your statement have anything to do with the subject at hand?? I never said it should be free, you're are literally making things up in your head.

That is like if a group of people where debating geo-politics and you came up, interrupted the conversation, and said "I like apples,  why do you hate apples?".

It makes you look like a brain damaged mental patient. Read before posting.

**Comment by Solarmax2** [comment]
I've made PR #1799, my hope is that runtime testing would reduce regressions like this. I do want to see this project thrive. :)
