### ISSUE TITLE
Freeze on double clicking layers tab

### ISSUE THREAD

**Issue by MathemanFlo** [armory3d/armortools#1786]
**ArmorPaint version:**
7f58e6b

**OS / GPU model:**
Win11 Directx11

**Issue description:**
ArmorPaint freezes whenever I double click on layers tab.

**Steps to reproduce:**
1. double click on layers tab
2. ArmorPaint will freeze
3. The non-complete callstack is:
>  	ArmorPaint.exe!gc_alloc(unsigned __int64 size) Zeile 78	C
 	ArmorPaint.exe!f32_array_create(int length) Zeile 371	C
 	ArmorPaint.exe!f32_array_create_from_raw(float * raw, int length) Zeile 396	C
 	ArmorPaint.exe!tab_materials_draw_slots(bool mini) Zeile 28082	C
 	ArmorPaint.exe!tab_materials_draw_mini(ui_handle * htab) Zeile 28048	C
 	ArmorPaint.exe!tab_materials_draw(ui_handle * htab) Zeile 28036	C
 	ArmorPaint.exe!ui_base_draw_sidebar() Zeile 30155	C
 	ArmorPaint.exe!ui_base_render() Zeile 30135	C
 	ArmorPaint.exe!_app_run_callbacks(callback_t_array * cbs) Zeile 5537	C
 	ArmorPaint.exe!app_render_2d() Zeile 5608	C
 	ArmorPaint.exe!app_render() Zeile 5602	C
 	ArmorPaint.exe!sys_render_callback() Zeile 10144	C
 	ArmorPaint.exe!_update(void * data) Zeile 478	C
 	ArmorPaint.exe!kinc_internal_update_callback() Zeile 429	C
 	ArmorPaint.exe!kinc_internal_frame() Zeile 523	C
 	ArmorPaint.exe!kinc_start() Zeile 537	C
 	ArmorPaint.exe!_kickstart() Zeile 5487	C
 	ArmorPaint.exe!kickstart(int argc, char * * argv) Zeile 307	C
 	ArmorPaint.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * lpCmdLine, int nCmdShow) Zeile 1321	C
 	[Externer Code]	

It gets stuck in `gc_alloc`. There it runs into some kind of deadlock.
From this point, rerunning ArmorPaint is not possible anymore. It will get stuck automatically whenever ArmorPaint is opened again. Only deleting the data directory and regenerating it will help.

**Comment by luboslenco** [comment]
Should be resolved, thanks for report! Still lots of testing to do.

**Comment by MathemanFlo** [comment]
You are welcome. Thank you for the quick fix. Great to see you big refactoring comes to an end and you can concentrate on the software itself again.
