### ISSUE TITLE
save after which crash

### ISSUE THREAD

**Issue by TumX31** [armory3d/armortools#1791]
version current
ArmorPaint.org - v1.0 alpha (2024-11-17) - eda9314
Windows - Direct3D11
Win 10, NVIDIA GeForce RTX 3080 Ti
installed on disk E in the ArmorPaint folder

launching the program via exe
save the file ctrl+shift+s
close the project
open the project via arm or via exe
make any change (left-click on the cube)
save the file ctrl+shift+s or ctrl+s
crash (often it saves, but sometimes it doesn't)

![image](https://github.com/user-attachments/assets/613cac71-4e02-4220-832a-b6b9e031edf5)

**Comment by TumX31** [comment]
on repeat
![image](https://github.com/user-attachments/assets/0e21b7f4-0a53-4da6-80aa-491369c6d6c4)

**Comment by luboslenco** [comment]
Should be resolved after https://github.com/armory3d/armortools/commit/e4f4ebcf83a8d87d919ad668a5aa7d8d10eb8377, thanks for report!
